In [1]:
import pandas as pd

In [2]:
df_data = pd.read_csv("../data/metro_paris_2020_2025.csv")

In [3]:
df_data.head()

                  time     badge                   station    type
0  2020-01-01 06:14:00  11567534    Lamarck - Caulaincourt  entrée
1  2020-01-01 06:17:00  42334134                     Liège  entrée
2  2020-01-01 06:28:00  33535600                  Glacière  entrée
3  2020-01-01 06:29:00  42914386                  Commerce  entrée
4  2020-01-01 06:31:00  74538562  Villejuif - Léo Lagrange  entrée

In [4]:
print("\nDescription du jeu de données")
df_data.info()

print("\nNombre de lignes : ", len(df_data), "\n")

print("Nombre de valeur null : ")
df_data.isnull().sum()

Description du jeu de données
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75839130 entries, 0 to 75839129
Data columns (total 4 columns):
 #   Column   Dtype
---  ------   -----
 0   time     object
 1   badge    int64
 2   station  object
 3   type     object
dtypes: int64(1), object(3)
memory usage: 2.3+ GB

Nombre de lignes :  75839130

Nombre de valeur null :

time       0
badge      0
station    0
type       0
dtype: int64

In [5]:
df_data.dtypes

print ("Rq : les colonnes time, station et type ne sont pas reconnu par pandas")

Rq : les colonnes time, station et type ne sont pas reconnu par pandas

In [6]:
print ("Changement du type de la colonne 'time' en type time")
       
df_data["time"] = pd.to_datetime(df_data["time"])

df_data["time"].min()

Changement du type de la colonne 'time' en type time

Timestamp('2020-01-01 06:14:00')

In [7]:
df_data["time"].max()

Timestamp('2025-12-31 22:17:00')

In [8]:
print("Nombre de variables par attributs de la table : ")
df_data.nunique()

Nombre de variables par attributs de la table :

time       1828273
badge       639077
station        304
type             2
dtype: int64

In [40]:
df_doublons = df_data.duplicated()
print ("Nombre de doublons : ",df_doublons.sum())

df_data[df_doublons]

Nombre de doublons :  15

                        time     badge              station    type
3841454  2020-04-03 07:40:00  13317836             Bastille  sortie
6704222  2020-06-18 14:23:00  63880929                Opéra  sortie
13196498 2021-01-14 08:39:00  37423176            Trocadéro  sortie
19101282 2021-06-16 08:59:00  64277056               Nation  sortie
33651374 2022-09-07 19:04:00  11405098           La Défense  sortie
37597828 2022-12-15 07:22:00  73538740            Pyramides  sortie
39398679 2023-02-07 07:41:00  51083346            Trocadéro  sortie
42250532 2023-05-02 07:42:00  48710772               Nation  sortie
50242393 2023-12-15 18:10:00  72682660      Aéroport d'Orly  sortie
53192618 2024-03-13 18:48:00  20979722      Porte d'Orléans  sortie
55889616 2024-05-29 07:33:00  64506325            Madeleine  sortie
56956841 2024-06-20 08:53:00  48187165               Balard  sortie
60299207 2024-10-10 17:29:00  52988132            Dugommier  sortie
66001031 2025-03-14 19:14:00  31242999   Saint-Denis Pleyel  sortie
67442190 2025-04-24 17:20:00  64506325  Porte de Versailles  sortie

In [23]:
df_anomalies= df_data.duplicated(["time","badge"])

In [24]:

df_all_anomalies = df_data[df_anomalies]

df_fraudeurs = df_all_anomalies["badge"].value_counts().reset_index()
df_fraudeurs.columns = ["badge", "nb_fraudes"]
df_fraudeurs

        badge  nb_fraudes
0    91661943          30
1     3267367          30
2    84381548          29
3    43949327          26
4    31242999          26
..        ...         ...
259  31796478           1
260  98863145           1
261  54131546           1
262  54771098           1
263  66451395           1

[264 rows x 2 columns]

In [30]:
df_nb_fraudes = (df_all_anomalies["badge"].value_counts()).to_frame(name = "occrurances")

In [31]:
df_nb_fraudes

          occrurances
91661943           30
3267367            30
84381548           29
43949327           26
31242999           26
...               ...
31796478            1
98863145            1
54131546            1
54771098            1
66451395            1

[264 rows x 1 columns]

In [37]:
df_nb_passages = df_data["badge"].value_counts()

In [41]:
df_nb_passages = df_nb_passages.sort_values(ascending=False)
df_nb_passages

41829492    7071
68776019    7060
18349085    6959
96352498    6926
652099      6925
            ...
28355804       1
86853994       1
84402743       1
76260194       1
73098114       1
Name: badge, Length: 639077, dtype: int64

In [43]:
df_data["station"].unique()

array(['Lamarck - Caulaincourt', 'Liège', 'Glacière', 'Commerce',
       'Villejuif - Léo Lagrange', "Porte d'Italie", 'Couronnes',
       'Jaurès', 'Porte de Saint-Ouen', "Gare d'Austerlitz",
       "Porte d'Auteuil", "Chemin d'Antony", "Église d'Auteuil",
       'Pyramides', "Trinité - d'Estienne d'Orves", 'Porte de Champerret',
       'Courcelles', 'Gallieni', 'Boulogne - Jean Jaurès',
       'Porte de Choisy', 'Chardon-Lagache', 'Porte de Clignancourt',
       "Porte d'Ivry", 'Pont de Neuilly', 'Mairie des Lilas', 'Boucicaut',
       'Falguière', 'Grands Boulevards', 'La Motte-Picquet - Grenelle',
       'Europe', 'Bastille', 'République', 'Alexandre Dumas',
       'Esplanade de la Défense', 'Malakoff - Rue Étienne Dolet',
       'Porte de Saint-Cloud', 'La Courneuve - 8 Mai 1945',
       'Porte de Vanves', 'Gare de Lyon', 'Champs-Élysées-Clemenceau',
       'Boulogne - Pont de Saint-Cloud',
       'Bobigny - Pantin - Raymond Queneau', 'Saint-Germain-des-Prés',
       'Temple', 'Porte de la Chapelle', 'Jacques Bonsergent',
       'La Défense', 'Porte des Lilas', 'Hôtel de Ville',
       'Porte de Vincennes', 'Cité', 'Châtelet', 'La Tour-Maubourg',
       'Saint-Placide', 'Cadet', 'Louvre - Rivoli', 'Rosny-Bois-Perrier',
       'Saint-Denis Pleyel', "Porte d'Orléans", 'Maubert - Mutualité',
       'La Fourche', 'Porte de Bagnolet', 'Mairie de Montreuil', 'Balard',
       'Villejuif - Gustave Roussy', 'Malakoff - Plateau de Vanves',
       'Villejuif - Louis Aragon', "Mairie d'Aubervilliers",
       'Porte de Charenton', 'Porte de Montreuil', "Mairie d'Issy",
       'Bobigny - Pablo Picasso', 'Créteil - Préfecture', 'Bercy',
       'Cour Saint-Émilion', 'Aimé Césaire', 'Nationale',
       'Denfert-Rochereau', 'Oberkampf', 'Gare du Nord', 'Exelmans',
       'Havre - Caumartin', 'Opéra', "Aéroport d'Orly", 'Lourmel',
       'Mirabeau', 'Château de Vincennes', 'Pyrénées', 'Cardinal Lemoine',
       'Daumesnil', 'Avenue Émile Zola', 'Raspail', 'Crimée',
       'Porte de Pantin', 'Chemin Vert', "Gare de l'Est", 'Le Peletier',
       'Odéon', 'Abbesses', "L'Haÿ-les-Roses", 'Bel-Air', 'Invalides',
       'Charles de Gaulle-Étoile', 'Jules Joffrin', 'Blanche', 'Jussieu',
       'Avron', 'Carrefour Pleyel', 'Pont de Levallois - Bécon',
       'Côteaux Beauclair', 'Saint-Lazare', 'Quatre-Septembre',
       'Place des Fêtes', 'Saint-Michel',
       'Palais Royal - Musée du Louvre', 'Créteil - Université',
       'Saint-Ouen', "Mairie d'Ivry", 'Porte de la Villette',
       'Saint-Sulpice', 'Mabillon', 'Buzenval', 'Campo-Formio',
       'Alma - Marceau', 'Pont Neuf', 'Corvisart',
       'Châtillon - Montrouge', 'Porte de Clichy', 'Saint-Marcel',
       'Nation', 'Pont de Sèvres', 'Poissonnière', 'Louise Michel',
       'Quai de la Rapée', 'Riquet', 'Philippe Auguste', 'Iéna',
       'Porte Dauphine', 'Gambetta', 'Pasteur', 'Michel-Ange - Auteuil',
       'Michel-Ange - Molitor', 'Issy - Val de Seine', 'Ranelagh',
       'Porte de Versailles', 'Corentin Celton', 'Rue Saint-Maur',
       'Saint-Denis - Université', 'Pereire', "Château d'Eau",
       'Boissière', 'Bir-Hakeim', 'Madeleine', 'Tuileries',
       "Chaussée d'Antin - La Fayette", 'Anatole France',
       "Fort d'Aubervilliers", 'Liberté', 'Père Lachaise',
       'Barbès - Rochechouart', 'Edgar Quinet', 'Convention', 'Rome',
       'Strasbourg - Saint-Denis', 'Marcel Sembat',
       'Réaumur - Sébastopol', 'Arts et Métiers', 'Stalingrad',
       'Montgallet', 'Sully - Morland', 'Franklin D. Roosevelt',
       'Barbara', 'Montparnasse - Bienvenüe', 'Faidherbe - Chaligny',
       'Église de Pantin', 'Place de Clichy',
       'Aubervilliers - Pantin - Quatre Chemins', "Place d'Italie",
       'Dugommier', 'Romainville - Carnot', 'Château Rouge', 'Plaisance',
       'Pont Cardinet', 'Marcadet - Poissonniers', 'Billancourt', 'Duroc',
       'Vaugirard', 'Quai de la Gare', 'Étienne Marcel', 'Villiers',
       'Gaîté', 'Montrouge', 'Pernety', 'Anvers', 'Trocadéro',
       'Télégraphe', 'Volontaires', 'Serge Gainsbourg', 'Dupleix',
       'Porte Maillot', 'Concorde', 'Censier - Daubenton',
       'Basilique de Saint-Denis', "Créteil - L'Échat", 'Pont Marie',
       'Hoche', 'Les Sablons', 'Saint-Sébastien - Froissart', 'Solférino',
       'Notre-Dame-de-Lorette', 'Monceau', 'Ternes', 'La Muette',
       'Place Monge', 'Rambuteau', 'Sèvres - Lecourbe', 'Voltaire',
       'Malesherbes', 'Maraîchers', 'Jourdain', 'Vavin', 'Colonel Fabien',
       'Charenton - Écoles', 'Tolbiac', 'Mairie de Saint-Ouen',
       'Louis Blanc', 'Victor Hugo', 'Bonne Nouvelle', 'Picpus',
       'Bibliothèque François Mitterrand', 'Porte Dorée', 'Goncourt',
       'Passy', 'Alésia', 'Villejuif - Paul Vaillant-Couturier',
       'Richard-Lenoir', 'George V', 'Saint-Georges', 'Kléber',
       'Richelieu - Drouot', 'Saint-Denis - Porte de Paris',
       'Rue des Boulets', 'Javel - André Citroën', 'Saint-Jacques',
       'Maisons-Alfort - Les Juilliottes',
       'École Vétérinaire de Maisons-Alfort', 'Guy Môquet', 'Wagram',
       'Maison Blanche', 'Les Halles', 'Saint-Augustin', 'Simplon',
       'Cluny - La Sorbonne', 'Varenne', 'Filles du Calvaire',
       'Rue du Bac', 'Cambronne', 'Notre-Dame-des-Champs', 'Rennes',
       'Saint-Philippe du Roule', 'École Militaire',
       'Saint-François-Xavier', 'Belleville', 'Maisons-Alfort - Stade',
       'Sentier', 'Montreuil - Hôpital', 'Saint-Ambroise',
       'Rue de la Pompe', 'Assemblée Nationale', 'Laumière',
       'Ménilmontant', 'Bréguet - Sabin', 'Olympiades', 'Corentin Cariou',
       'Jasmin', 'Saint-Mandé', 'Charonne', 'Félix Faure', 'Argentine',
       'Les Gobelins', 'Garibaldi', 'Château-Landon', 'Ourcq',
       'Sèvres - Babylone', 'Bagneux', 'Mouton-Duvernet', 'Bourse',
       'Croix de Chavaux', 'Bérault', 'Chevaleret', 'Reuilly - Diderot',
       'Michel Bizot', 'Robespierre', 'La Dhuys', 'Ledru-Rollin',
       'Pierre et Marie Curie', 'La Chapelle', 'Charles Michels',
       'Parmentier', 'Pigalle', 'Saint-Paul', 'Vaneau', 'Miromesnil',
       'Ségur'], dtype=object)

In [47]:
df_Seine = df_data[df_data["station"] == "Issy - Val de Seine"]

In [51]:
df_Seine.shape[0]/df_data.shape[0]*100

0.15880983866771678

In [52]:
df_Anthony = df_data[df_data["station"]== "Chemin d'Antony"]

In [54]:
df_Anthony.shape[0]/df_data.shape[0]*100

0.16497156547022626