In [1]:
import pandas as pd

In [2]:
df_data = pd.read_csv("../data/metro_paris_2020_2025.csv")

In [3]:
df_data.head()

                  time     badge                   station    type
0  2020-01-01 06:14:00  11567534    Lamarck - Caulaincourt  entrée
1  2020-01-01 06:17:00  42334134                     Liège  entrée
2  2020-01-01 06:28:00  33535600                  Glacière  entrée
3  2020-01-01 06:29:00  42914386                  Commerce  entrée
4  2020-01-01 06:31:00  74538562  Villejuif - Léo Lagrange  entrée

In [4]:
print("\nDescription du jeu de données")
df_data.info()

print("\nNombre de lignes : ", len(df_data), "\n")

print("Nombre de valeur null : ")
df_data.isnull().sum()

Description du jeu de données
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75839130 entries, 0 to 75839129
Data columns (total 4 columns):
 #   Column   Dtype
---  ------   -----
 0   time     object
 1   badge    int64
 2   station  object
 3   type     object
dtypes: int64(1), object(3)
memory usage: 2.3+ GB

Nombre de lignes :  75839130

Nombre de valeur null :

time       0
badge      0
station    0
type       0
dtype: int64

In [5]:
df_data.dtypes

print ("Rq : les colonnes time, station et type ne sont pas reconnu par pandas")

Rq : les colonnes time, station et type ne sont pas reconnu par pandas

In [6]:
print ("Changement du type de la colonne 'time' en type time")
       
df_data["time"] = pd.to_datetime(df_data["time"])

df_data["time"].min()

Changement du type de la colonne 'time' en type time

Timestamp('2020-01-01 06:14:00')

In [7]:
df_data["time"].max()

Timestamp('2025-12-31 22:17:00')

In [8]:
print("Nombre de variables par attributs de la table : ")
df_data.nunique()

Nombre de variables par attributs de la table :

time       1828273
badge       639077
station        304
type             2
dtype: int64

In [40]:
df_doublons = df_data.duplicated()
print ("Nombre de doublons : ",df_doublons.sum())

df_data[df_doublons]

Nombre de doublons :  15

                        time     badge              station    type
3841454  2020-04-03 07:40:00  13317836             Bastille  sortie
6704222  2020-06-18 14:23:00  63880929                Opéra  sortie
13196498 2021-01-14 08:39:00  37423176            Trocadéro  sortie
19101282 2021-06-16 08:59:00  64277056               Nation  sortie
33651374 2022-09-07 19:04:00  11405098           La Défense  sortie
37597828 2022-12-15 07:22:00  73538740            Pyramides  sortie
39398679 2023-02-07 07:41:00  51083346            Trocadéro  sortie
42250532 2023-05-02 07:42:00  48710772               Nation  sortie
50242393 2023-12-15 18:10:00  72682660      Aéroport d'Orly  sortie
53192618 2024-03-13 18:48:00  20979722      Porte d'Orléans  sortie
55889616 2024-05-29 07:33:00  64506325            Madeleine  sortie
56956841 2024-06-20 08:53:00  48187165               Balard  sortie
60299207 2024-10-10 17:29:00  52988132            Dugommier  sortie
66001031 2025-03-14 19:14:00  31242999   Saint-Denis Pleyel  sortie
67442190 2025-04-24 17:20:00  64506325  Porte de Versailles  sortie

In [23]:
df_anomalies= df_data.duplicated(["time","badge"])

In [24]:

df_all_anomalies = df_data[df_anomalies]

df_fraudeurs = df_all_anomalies["badge"].value_counts().reset_index()
df_fraudeurs.columns = ["badge", "nb_fraudes"]
df_fraudeurs

        badge  nb_fraudes
0    91661943          30
1     3267367          30
2    84381548          29
3    43949327          26
4    31242999          26
..        ...         ...
259  31796478           1
260  98863145           1
261  54131546           1
262  54771098           1
263  66451395           1

[264 rows x 2 columns]

In [30]:
df_nb_fraudes = (df_all_anomalies["badge"].value_counts()).to_frame(name = "occrurances")

In [31]:
df_nb_fraudes

          occrurances
91661943           30
3267367            30
84381548           29
43949327           26
31242999           26
...               ...
31796478            1
98863145            1
54131546            1
54771098            1
66451395            1

[264 rows x 1 columns]

In [37]:
df_nb_passages = df_data["badge"].value_counts()

In [41]:
df_nb_passages = df_nb_passages.sort_values(ascending=False)
df_nb_passages

41829492    7071
68776019    7060
18349085    6959
96352498    6926
652099      6925
            ...
28355804       1
86853994       1
84402743       1
76260194       1
73098114       1
Name: badge, Length: 639077, dtype: int64

In [43]:
df_data["station"].unique()

array(['Lamarck - Caulaincourt', 'Liège', 'Glacière', 'Commerce',
       'Villejuif - Léo Lagrange', "Porte d'Italie", 'Couronnes',
       'Jaurès', 'Porte de Saint-Ouen', "Gare d'Austerlitz",
       "Porte d'Auteuil", "Chemin d'Antony", "Église d'Auteuil",
       'Pyramides', "Trinité - d'Estienne d'Orves", 'Porte de Champerret',
       'Courcelles', 'Gallieni', 'Boulogne - Jean Jaurès',
       'Porte de Choisy', 'Chardon-Lagache', 'Porte de Clignancourt',
       "Porte d'Ivry", 'Pont de Neuilly', 'Mairie des Lilas', 'Boucicaut',
       'Falguière', 'Grands Boulevards', 'La Motte-Picquet - Grenelle',
       'Europe', 'Bastille', 'République', 'Alexandre Dumas',
       'Esplanade de la Défense', 'Malakoff - Rue Étienne Dolet',
       'Porte de Saint-Cloud', 'La Courneuve - 8 Mai 1945',
       'Porte de Vanves', 'Gare de Lyon', 'Champs-Élysées-Clemenceau',
       'Boulogne - Pont de Saint-Cloud',
       'Bobigny - Pantin - Raymond Queneau', 'Saint-Germain-des-Prés',
       'Temple', 'Porte de la Chapelle', 'Jacques Bonsergent',
       'La Défense', 'Porte des Lilas', 'Hôtel de Ville',
       'Porte de Vincennes', 'Cité', 'Châtelet', 'La Tour-Maubourg',
       'Saint-Placide', 'Cadet', 'Louvre - Rivoli', 'Rosny-Bois-Perrier',
       'Saint-Denis Pleyel', "Porte d'Orléans", 'Maubert - Mutualité',
       'La Fourche', 'Porte de Bagnolet', 'Mairie de Montreuil', 'Balard',
       'Villejuif - Gustave Roussy', 'Malakoff - Plateau de Vanves',
       'Villejuif - Louis Aragon', "Mairie d'Aubervilliers",
       'Porte de Charenton', 'Porte de Montreuil', "Mairie d'Issy",
       'Bobigny - Pablo Picasso', 'Créteil - Préfecture', 'Bercy',
       'Cour Saint-Émilion', 'Aimé Césaire', 'Nationale',
       'Denfert-Rochereau', 'Oberkampf', 'Gare du Nord', 'Exelmans',
       'Havre - Caumartin', 'Opéra', "Aéroport d'Orly", 'Lourmel',
       'Mirabeau', 'Château de Vincennes', 'Pyrénées', 'Cardinal Lemoine',
       'Daumesnil', 'Avenue Émile Zola', 'Raspail', 'Crimée',
       'Porte de Pantin', 'Chemin Vert', "Gare de l'Est", 'Le Peletier',
       'Odéon', 'Abbesses', "L'Haÿ-les-Roses", 'Bel-Air', 'Invalides',
       'Charles de Gaulle-Étoile', 'Jules Joffrin', 'Blanche', 'Jussieu',
       'Avron', 'Carrefour Pleyel', 'Pont de Levallois - Bécon',
       'Côteaux Beauclair', 'Saint-Lazare', 'Quatre-Septembre',
       'Place des Fêtes', 'Saint-Michel',
       'Palais Royal - Musée du Louvre', 'Créteil - Université',
       'Saint-Ouen', "Mairie d'Ivry", 'Porte de la Villette',
       'Saint-Sulpice', 'Mabillon', 'Buzenval', 'Campo-Formio',
       'Alma - Marceau', 'Pont Neuf', 'Corvisart',
       'Châtillon - Montrouge', 'Porte de Clichy', 'Saint-Marcel',
       'Nation', 'Pont de Sèvres', 'Poissonnière', 'Louise Michel',
       'Quai de la Rapée', 'Riquet', 'Philippe Auguste', 'Iéna',
       'Porte Dauphine', 'Gambetta', 'Pasteur', 'Michel-Ange - Auteuil',
       'Michel-Ange - Molitor', 'Issy - Val de Seine', 'Ranelagh',
       'Porte de Versailles', 'Corentin Celton', 'Rue Saint-Maur',
       'Saint-Denis - Université', 'Pereire', "Château d'Eau",
       'Boissière', 'Bir-Hakeim', 'Madeleine', 'Tuileries',
       "Chaussée d'Antin - La Fayette", 'Anatole France',
       "Fort d'Aubervilliers", 'Liberté', 'Père Lachaise',
       'Barbès - Rochechouart', 'Edgar Quinet', 'Convention', 'Rome',
       'Strasbourg - Saint-Denis', 'Marcel Sembat',
       'Réaumur - Sébastopol', 'Arts et Métiers', 'Stalingrad',
       'Montgallet', 'Sully - Morland', 'Franklin D. Roosevelt',
       'Barbara', 'Montparnasse - Bienvenüe', 'Faidherbe - Chaligny',
       'Église de Pantin', 'Place de Clichy',
       'Aubervilliers - Pantin - Quatre Chemins', "Place d'Italie",
       'Dugommier', 'Romainville - Carnot', 'Château Rouge', 'Plaisance',
       'Pont Cardinet', 'Marcadet - Poissonniers', 'Billancourt', 'Duroc',
       'Vaugirard', 'Quai de la Gare', 'Étienne Marcel', 'Villiers',
       'Gaîté', 'Montrouge', 'Pernety', 'Anvers', 'Trocadéro',
       'Télégraphe', 'Volontaires', 'Serge Gainsbourg', 'Dupleix',
       'Porte Maillot', 'Concorde', 'Censier - Daubenton',
       'Basilique de Saint-Denis', "Créteil - L'Échat", 'Pont Marie',
       'Hoche', 'Les Sablons', 'Saint-Sébastien - Froissart', 'Solférino',
       'Notre-Dame-de-Lorette', 'Monceau', 'Ternes', 'La Muette',
       'Place Monge', 'Rambuteau', 'Sèvres - Lecourbe', 'Voltaire',
       'Malesherbes', 'Maraîchers', 'Jourdain', 'Vavin', 'Colonel Fabien',
       'Charenton - Écoles', 'Tolbiac', 'Mairie de Saint-Ouen',
       'Louis Blanc', 'Victor Hugo', 'Bonne Nouvelle', 'Picpus',
       'Bibliothèque François Mitterrand', 'Porte Dorée', 'Goncourt',
       'Passy', 'Alésia', 'Villejuif - Paul Vaillant-Couturier',
       'Richard-Lenoir', 'George V', 'Saint-Georges', 'Kléber',
       'Richelieu - Drouot', 'Saint-Denis - Porte de Paris',
       'Rue des Boulets', 'Javel - André Citroën', 'Saint-Jacques',
       'Maisons-Alfort - Les Juilliottes',
       'École Vétérinaire de Maisons-Alfort', 'Guy Môquet', 'Wagram',
       'Maison Blanche', 'Les Halles', 'Saint-Augustin', 'Simplon',
       'Cluny - La Sorbonne', 'Varenne', 'Filles du Calvaire',
       'Rue du Bac', 'Cambronne', 'Notre-Dame-des-Champs', 'Rennes',
       'Saint-Philippe du Roule', 'École Militaire',
       'Saint-François-Xavier', 'Belleville', 'Maisons-Alfort - Stade',
       'Sentier', 'Montreuil - Hôpital', 'Saint-Ambroise',
       'Rue de la Pompe', 'Assemblée Nationale', 'Laumière',
       'Ménilmontant', 'Bréguet - Sabin', 'Olympiades', 'Corentin Cariou',
       'Jasmin', 'Saint-Mandé', 'Charonne', 'Félix Faure', 'Argentine',
       'Les Gobelins', 'Garibaldi', 'Château-Landon', 'Ourcq',
       'Sèvres - Babylone', 'Bagneux', 'Mouton-Duvernet', 'Bourse',
       'Croix de Chavaux', 'Bérault', 'Chevaleret', 'Reuilly - Diderot',
       'Michel Bizot', 'Robespierre', 'La Dhuys', 'Ledru-Rollin',
       'Pierre et Marie Curie', 'La Chapelle', 'Charles Michels',
       'Parmentier', 'Pigalle', 'Saint-Paul', 'Vaneau', 'Miromesnil',
       'Ségur'], dtype=object)

In [47]:
df_Seine = df_data[df_data["station"] == "Issy - Val de Seine"]

In [51]:
df_Seine.shape[0]/df_data.shape[0]*100

0.15880983866771678

In [52]:
df_Anthony = df_data[df_data["station"]== "Chemin d'Antony"]

In [54]:
df_Anthony.shape[0]/df_data.shape[0]*100

0.16497156547022626

In [2]:
df_data_metro = pd.read_csv("../data/metro-france.csv")

df_data_metro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 708 entries, 0 to 707
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID Line             708 non-null    int64
 1   Libelle Line        708 non-null    object
 2   Libelle station     708 non-null    object
 3   Longitude           708 non-null    float64
 4   Latitude            708 non-null    float64
 5   finish              708 non-null    int64
 6   Commune nom         708 non-null    object
 7   Commune code Insee  708 non-null    int64
dtypes: float64(2), int64(3), object(3)
memory usage: 44.4+ KB

In [39]:
df_data_metro.columns

Index(['ID Line', 'Libelle Line', 'Libelle station', 'Longitude', 'Latitude',
       'finish', 'Commune nom', 'Commune code Insee'],
      dtype='object')

In [40]:
sorted(df_data_metro['Commune nom'].unique())

['Antony',
 'Asnières-sur-Seine',
 'Aubervilliers',
 'Aulnay-sous-Bois',
 'Bagneux',
 'Bagnolet',
 'Blagnac',
 'Bobigny',
 'Bois-Colombes',
 'Bondy',
 'Boulogne-Billancourt',
 'Cachan',
 'Caluire-et-Cuire',
 'Champigny-sur-Marne',
 'Champs-sur-Marne',
 'Charenton-le-Pont',
 'Chelles',
 'Chevilly-Larue',
 'Châtillon',
 'Clamart',
 'Clichy',
 'Clichy-sous-Bois',
 'Colomiers',
 'Courbevoie',
 'Croix',
 'Créteil',
 'Drancy',
 'Dugny',
 'Fontenay-sous-Bois',
 'Gennevilliers',
 'Gonesse',
 'Guyancourt',
 'Issy-les-Moulineaux',
 'Ivry-sur-Seine',
 "L'Haÿ-les-Roses",
 'La Courneuve',
 'Labège',
 'Le Blanc-Mesnil',
 'Le Bourget',
 'Le Kremlin-Bicêtre',
 'Le Mesnil-Amelot',
 'Le Perreux-sur-Marne',
 'Levallois-Perret',
 'Lilas',
 'Lille',
 'Lyon',
 'Maisons-Alfort',
 'Malakoff',
 'Marseille',
 'Massy',
 'Mons-en-Barœul',
 'Montreuil',
 'Montrouge',
 'Nanterre',
 'Neuilly-sur-Seine',
 'Noisy-le-Sec',
 'Orsay',
 'Oullins',
 'Palaiseau',
 'Pantin',
 'Paray-Vieille-Poste',
 'Paris 10ème',
 'Paris 11ème',
 'Paris 12ème',
 'Paris 13ème',
 'Paris 14ème',
 'Paris 15ème',
 'Paris 16ème',
 'Paris 17ème',
 'Paris 18ème',
 'Paris 19ème',
 'Paris 1er',
 'Paris 20ème',
 'Paris 2ème',
 'Paris 3ème',
 'Paris 4ème',
 'Paris 5ème',
 'Paris 6ème',
 'Paris 7ème',
 'Paris 8ème',
 'Paris 9ème',
 'Puteaux',
 'Ramonville-Saint-Agne',
 'Rennes',
 'Romainville',
 'Rosny-sous-Bois',
 'Roubaix',
 'Rueil-Malmaison',
 'Saclay',
 'Saint-Cloud',
 'Saint-Denis',
 'Saint-Genis-Laval',
 'Saint-Jacques-de-la-Lande',
 'Saint-Mandé',
 'Saint-Maur-des-Fossés',
 'Saint-Ouen',
 'Sevran',
 'Thiais',
 'Toulouse',
 'Tourcoing',
 'Vaulx-en-Velin',
 'Versailles',
 'Villejuif',
 "Villeneuve-d'Ascq",
 'Villepinte',
 'Villeurbanne',
 'Villiers-sur-Marne',
 'Vincennes',
 'Vitry-sur-Seine',
 'Vénissieux',
 'Wasquehal']

In [3]:
# 1. Définition des listes
liste_stations = [
    'Lamarck - Caulaincourt', 'Liège', 'Glacière', 'Commerce',
    'Villejuif - Léo Lagrange', "Porte d'Italie", 'Couronnes',
    'Jaurès', 'Porte de Saint-Ouen', "Gare d'Austerlitz",
    "Porte d'Auteuil", "Chemin d'Antony", "Église d'Auteuil",
    'Pyramides', "Trinité - d'Estienne d'Orves", 'Porte de Champerret',
    'Courcelles', 'Gallieni', 'Boulogne - Jean Jaurès',
    'Porte de Choisy', 'Chardon-Lagache', 'Porte de Clignancourt',
    "Porte d'Ivry", 'Pont de Neuilly', 'Mairie des Lilas', 'Boucicaut',
    'Falguière', 'Grands Boulevards', 'La Motte-Picquet - Grenelle',
    'Europe', 'Bastille', 'République', 'Alexandre Dumas',
    'Esplanade de la Défense', 'Malakoff - Rue Étienne Dolet',
    'Porte de Saint-Cloud', 'La Courneuve - 8 Mai 1945',
    'Porte de Vanves', 'Gare de Lyon', 'Champs-Élysées-Clemenceau',
    'Boulogne - Pont de Saint-Cloud',
    'Bobigny - Pantin - Raymond Queneau', 'Saint-Germain-des-Prés',
    'Temple', 'Porte de la Chapelle', 'Jacques Bonsergent',
    'La Défense', 'Porte des Lilas', 'Hôtel de Ville',
    'Porte de Vincennes', 'Cité', 'Châtelet', 'La Tour-Maubourg',
    'Saint-Placide', 'Cadet', 'Louvre - Rivoli', 'Rosny-Bois-Perrier',
    'Saint-Denis Pleyel', "Porte d'Orléans", 'Maubert - Mutualité',
    'La Fourche', 'Porte de Bagnolet', 'Mairie de Montreuil', 'Balard',
    'Villejuif - Gustave Roussy', 'Malakoff - Plateau de Vanves',
    'Villejuif - Louis Aragon', "Mairie d'Aubervilliers",
    'Porte de Charenton', 'Porte de Montreuil', "Mairie d'Issy",
    'Bobigny - Pablo Picasso', 'Créteil - Préfecture', 'Bercy',
    'Cour Saint-Émilion', 'Aimé Césaire', 'Nationale',
    'Denfert-Rochereau', 'Oberkampf', 'Gare du Nord', 'Exelmans',
    'Havre - Caumartin', 'Opéra', "Aéroport d'Orly", 'Lourmel',
    'Mirabeau', 'Château de Vincennes', 'Pyrénées', 'Cardinal Lemoine',
    'Daumesnil', 'Avenue Émile Zola', 'Raspail', 'Crimée',
    'Porte de Pantin', 'Chemin Vert', "Gare de l'Est", 'Le Peletier',
    'Odéon', 'Abbesses', "L'Haÿ-les-Roses", 'Bel-Air', 'Invalides',
    'Charles de Gaulle-Étoile', 'Jules Joffrin', 'Blanche', 'Jussieu',
    'Avron', 'Carrefour Pleyel', 'Pont de Levallois - Bécon',
    'Côteaux Beauclair', 'Saint-Lazare', 'Quatre-Septembre',
    'Place des Fêtes', 'Saint-Michel',
    'Palais Royal - Musée du Louvre', 'Créteil - Université',
    'Saint-Ouen', "Mairie d'Ivry", 'Porte de la Villette',
    'Saint-Sulpice', 'Mabillon', 'Buzenval', 'Campo-Formio',
    'Alma - Marceau', 'Pont Neuf', 'Corvisart',
    'Châtillon - Montrouge', 'Porte de Clichy', 'Saint-Marcel',
    'Nation', 'Pont de Sèvres', 'Poissonnière', 'Louise Michel',
    'Quai de la Rapée', 'Riquet', 'Philippe Auguste', 'Iéna',
    'Porte Dauphine', 'Gambetta', 'Pasteur', 'Michel-Ange - Auteuil',
    'Michel-Ange - Molitor', 'Issy - Val de Seine', 'Ranelagh',
    'Porte de Versailles', 'Corentin Celton', 'Rue Saint-Maur',
    'Saint-Denis - Université', 'Pereire', "Château d'Eau",
    'Boissière', 'Bir-Hakeim', 'Madeleine', 'Tuileries',
    "Chaussée d'Antin - La Fayette", 'Anatole France',
    "Fort d'Aubervilliers", 'Liberté', 'Père Lachaise',
    'Barbès - Rochechouart', 'Edgar Quinet', 'Convention', 'Rome',
    'Strasbourg - Saint-Denis', 'Marcel Sembat',
    'Réaumur - Sébastopol', 'Arts et Métiers', 'Stalingrad',
    'Montgallet', 'Sully - Morland', 'Franklin D. Roosevelt',
    'Barbara', 'Montparnasse - Bienvenüe', 'Faidherbe - Chaligny',
    'Église de Pantin', 'Place de Clichy',
    'Aubervilliers - Pantin - Quatre Chemins', "Place d'Italie",
    'Dugommier', 'Romainville - Carnot', 'Château Rouge', 'Plaisance',
    'Pont Cardinet', 'Marcadet - Poissonniers', 'Billancourt', 'Duroc',
    'Vaugirard', 'Quai de la Gare', 'Étienne Marcel', 'Villiers',
    'Gaîté', 'Montrouge', 'Pernety', 'Anvers', 'Trocadéro',
    'Télégraphe', 'Volontaires', 'Serge Gainsbourg', 'Dupleix',
    'Porte Maillot', 'Concorde', 'Censier - Daubenton',
    'Basilique de Saint-Denis', "Créteil - L'Échat", 'Pont Marie',
    'Hoche', 'Les Sablons', 'Saint-Sébastien - Froissart', 'Solférino',
    'Notre-Dame-de-Lorette', 'Monceau', 'Ternes', 'La Muette',
    'Place Monge', 'Rambuteau', 'Sèvres - Lecourbe', 'Voltaire',
    'Malesherbes', 'Maraîchers', 'Jourdain', 'Vavin', 'Colonel Fabien',
    'Charenton - Écoles', 'Tolbiac', 'Mairie de Saint-Ouen',
    'Louis Blanc', 'Victor Hugo', 'Bonne Nouvelle', 'Picpus',
    'Bibliothèque François Mitterrand', 'Porte Dorée', 'Goncourt',
    'Passy', 'Alésia', 'Villejuif - Paul Vaillant-Couturier',
    'Richard-Lenoir', 'George V', 'Saint-Georges', 'Kléber',
    'Richelieu - Drouot', 'Saint-Denis - Porte de Paris',
    'Rue des Boulets', 'Javel - André Citroën', 'Saint-Jacques',
    'Maisons-Alfort - Les Juilliottes',
    'École Vétérinaire de Maisons-Alfort', 'Guy Môquet', 'Wagram',
    'Maison Blanche', 'Les Halles', 'Saint-Augustin', 'Simplon',
    'Cluny - La Sorbonne', 'Varenne', 'Filles du Calvaire',
    'Rue du Bac', 'Cambronne', 'Notre-Dame-des-Champs', 'Rennes',
    'Saint-Philippe du Roule', 'École Militaire',
    'Saint-François-Xavier', 'Belleville', 'Maisons-Alfort - Stade',
    'Sentier', 'Montreuil - Hôpital', 'Saint-Ambroise',
    'Rue de la Pompe', 'Assemblée Nationale', 'Laumière',
    'Ménilmontant', 'Bréguet - Sabin', 'Olympiades', 'Corentin Cariou',
    'Jasmin', 'Saint-Mandé', 'Charonne', 'Félix Faure', 'Argentine',
    'Les Gobelins', 'Garibaldi', 'Château-Landon', 'Ourcq',
    'Sèvres - Babylone', 'Bagneux', 'Mouton-Duvernet', 'Bourse',
    'Croix de Chavaux', 'Bérault', 'Chevaleret', 'Reuilly - Diderot',
    'Michel Bizot', 'Robespierre', 'La Dhuys', 'Ledru-Rollin',
    'Pierre et Marie Curie', 'La Chapelle', 'Charles Michels',
    'Parmentier', 'Pigalle', 'Saint-Paul', 'Vaneau', 'Miromesnil',
    'Ségur'
]

liste_communes = [
    # Paris intra-muros
    'Paris 1er', 'Paris 2ème', 'Paris 3ème', 'Paris 4ème', 'Paris 5ème',
    'Paris 6ème', 'Paris 7ème', 'Paris 8ème', 'Paris 9ème', 'Paris 10ème',
    'Paris 11ème', 'Paris 12ème', 'Paris 13ème', 'Paris 14ème', 'Paris 15ème',
    'Paris 16ème', 'Paris 17ème', 'Paris 18ème', 'Paris 19ème', 'Paris 20ème',
    
    # Banlieue / Petite couronne (stations manquantes)
    'Antony','Asnières-sur-Seine','Aubervilliers','Bagneux','Bagnolet','Bobigny','Boulogne-Billancourt','Charenton-le-Pont',
    'Châtillon','Clichy','Courbevoie','Créteil','Issy-les-Moulineaux','Ivry-sur-Seine', "L'Haÿ-les-Roses", 'La Courneuve','Le Kremlin-Bicêtre',
    'Levallois-Perret','Lilas','Maisons-Alfort','Malakoff','Montreuil','Montrouge','Neuilly-sur-Seine','Noisy-le-Sec','Pantin','Paray-Vieille-Poste','Puteaux',
    'Romainville','Rosny-sous-Bois','Saint-Cloud','Saint-Denis','Saint-Mandé','Saint-Ouen','Vincennes','Villejuif'
]

import unicodedata, re
# 0. Normalisation des noms de stations 
def normaliser(nom):
    nom = unicodedata.normalize("NFKD", nom).encode("ascii", "ignore").decode()
    nom = re.sub(r"[-'’]", " ", nom.lower())
    return re.sub(r"\s+", " ", nom).strip()
df_data_metro_paris = df_data_metro[df_data_metro["Commune nom"].isin(liste_communes)]

In [42]:
df_data_metro[df_data_metro["Commune nom"].isin(liste_communes)]

,ID Line,Libelle Line,Libelle station,Longitude,Latitude,finish,Commune nom,Commune code Insee
205,13,1,La Défense (Grande Arche),2.237988,48.891818,1,Puteaux,92062
206,13,1,Esplanade de la Défense,2.249904,48.888332,1,Courbevoie,92026
207,13,1,Pont de Neuilly,2.258523,48.885499,1,Neuilly-sur-Seine,92051
208,13,1,Les Sablons,2.271905,48.881291,1,Neuilly-sur-Seine,92051
209,13,1,Porte Maillot,2.282584,48.878163,1,Paris 17ème,75117
...,...,...,...,...,...,...,...,...
677,37,16,La Courneuve - Six Routes,2.384100,48.928600,0,La Courneuve,93027
693,38,17,La Courneuve - Six Routes,2.384100,48.928600,0,La Courneuve,93027
694,38,17,Saint-Denis Pleyel,2.346700,48.917200,0,Saint-Denis,93200
703,39,18,Antonypole,2.309400,48.735000,0,Antony,92002
704,39,18,Aéroport d’Orly,2.362600,48.728200,0,Paray-Vieille-Poste,91479

In [43]:


# 2. Filtrage correct avec le symbole &
df_data_cible = df_data_metro[
    (df_data_metro["Libelle station"].isin(liste_stations)) & 
    (df_data_metro["Commune nom"].isin(liste_communes))
]

In [44]:
df_data_cible

,ID Line,Libelle Line,Libelle station,Longitude,Latitude,finish,Commune nom,Commune code Insee
206,13,1,Esplanade de la Défense,2.249904,48.888332,1,Courbevoie,92026
207,13,1,Pont de Neuilly,2.258523,48.885499,1,Neuilly-sur-Seine,92051
208,13,1,Les Sablons,2.271905,48.881291,1,Neuilly-sur-Seine,92051
209,13,1,Porte Maillot,2.282584,48.878163,1,Paris 17ème,75117
210,13,1,Argentine,2.289435,48.875667,1,Paris 17ème,75117
...,...,...,...,...,...,...,...,...
664,36,15,Saint-Denis Pleyel,2.346700,48.917200,0,Saint-Denis,93200
666,36,15,Mairie d'Aubervilliers,2.380851,48.913731,0,Aubervilliers,93001
667,36,15,Fort d'Aubervilliers,2.404188,48.914708,0,Aubervilliers,93001
676,37,16,Saint-Denis Pleyel,2.346700,48.917200,0,Saint-Denis,93200
694,38,17,Saint-Denis Pleyel,2.346700,48.917200,0,Saint-Denis,93200

In [45]:

print ("statition de data metro : ")
print(sorted(df_data_metro_paris["Libelle station"].unique()))
print (len(df_data_metro_paris["Libelle station"].unique()))
print ("\n statition des donées de tickets :")
print (sorted( liste_stations))
print (len(liste_stations))

statition de data metro :
['Abbesses', 'Aimé Césaire', 'Alexandre Dumas', 'Alma - Marceau', 'Alésia', 'Anatole France', 'Antonypole', 'Anvers', 'Argentine', 'Arts et Métiers', 'Assemblée Nationale', 'Aubervilliers-Pantin Quatre Chemins', 'Avenue Émile Zola', 'Avron', 'Aéroport d’Orly', 'Bagneux - Lucie Aubrac', 'Balard', 'Barbara', 'Barbès - Rochechouart', 'Basilique de Saint-Denis', 'Bastille', 'Bel-Air', 'Belleville', 'Bercy', 'Bibliothèque François Mitterrand', 'Billancourt', 'Bir-Hakeim', 'Blanche', 'Bobigny Pablo Picasso', 'Bobigny-Pantin - Raymond Queneau', 'Boissière', 'Bolivar', 'Bonne Nouvelle', 'Botzaris', 'Boucicaut', 'Boulogne Jean Jaurès', 'Boulogne Pont de Saint-Cloud', 'Bourse', 'Brochant', 'Bréguet-Sabin', 'Buttes Chaumont', 'Buzenval', 'Bécon-les-Bruyères', 'Bérault', 'Cadet', 'Cambronne', 'Campo-Formio', 'Cardinal Lemoine', 'Carrefour Pleyel', 'Censier - Daubenton', 'Champs-Élysées - Clemenceau', 'Chardon Lagache', 'Charenton - Écoles', 'Charles Michels', 'Charles de Gaulle - Etoile', 'Charonne', "Chaussée d'Antin - La Fayette", 'Chemin Vert', 'Chevaleret', 'Château Landon', 'Château Rouge', "Château d'Eau", 'Château de Vincennes', 'Châtelet', 'Châtillon-Montrouge', 'Cité', 'Cluny - La Sorbonne', 'Colonel Fabien', 'Commerce', 'Concorde', 'Convention', 'Corentin Cariou', 'Corentin Celton', 'Corvisart', 'Coteaux beauclair', 'Cour Saint-Emilion', 'Courcelles', 'Couronnes', 'Crimée', 'Croix de Chavaux', "Créteil - L'Échat", 'Créteil - Préfecture', 'Créteil - Université', 'Danube', 'Daumesnil', 'Denfert-Rochereau', 'Dugommier', 'Dupleix', 'Duroc', 'Ecole Vétérinaire de Maisons-Alfort', 'Edgar Quinet', 'Esplanade de la Défense', 'Etienne Marcel', 'Europe', 'Exelmans', 'Faidherbe - Chaligny', 'Falguière', 'Filles du Calvaire', "Fort d'Aubervilliers", 'Franklin D. Roosevelt', 'Front Populaire', 'Félix Faure', 'Gabriel Péri', 'Gallieni', 'Gambetta', "Gare d'Austerlitz", 'Gare de Lyon', "Gare de l'Est", 'Gare du Nord', 'Garibaldi', 'Gaîté', 'George V', 'Glacière', 'Goncourt', 'Grands Boulevards', 'Guy Môquet', 'Havre-Caumartin', 'Hoche', 'Hôpital bicêtre', 'Hôtel de Ville', 'Invalides', 'Issy RER', 'Iéna', 'Jacques Bonsergent', 'Jasmin', 'Jaurès', 'Javel - André Citroën', 'Jourdain', 'Jules Joffrin', 'Jussieu', 'Kléber', 'La Chapelle', 'La Courneuve - 8 Mai 1945', 'La Courneuve - Six Routes', 'La Défense (Grande Arche)', 'La Fourche', 'La Motte-Picquet - Grenelle', 'La Muette', 'La Tour-Maubourg', 'La dhuys', 'Lamarck - Caulaincourt', 'Laumière', 'Le Kremlin-Bicêtre', 'Le Peletier', 'Le Vert de Maisons', 'Ledru-Rollin', 'Les Agnettes', 'Les Gobelins', 'Les Halles', 'Les Sablons', 'Liberté', 'Liège', 'Louis Blanc', 'Louise Michel', 'Lourmel', 'Louvre - Rivoli', 'L’Haÿ-les-roses', 'Mabillon', 'Madeleine', "Mairie d'Aubervilliers", "Mairie d'Issy", "Mairie d'Ivry", 'Mairie de Clichy', 'Mairie de Montreuil', 'Mairie de Montrouge', 'Mairie de Saint-Ouen', 'Mairie des Lilas', 'Maison Blanche', 'Maisons-Alfort - Les Juilliottes', 'Maisons-Alfort - Stade', 'Malakoff - Plateau de Vanves', 'Malakoff - Rue Etienne Dolet', 'Malesherbes', 'Maraîchers', 'Marcadet - Poissonniers', 'Marcel Sembat', 'Marx Dormoy', 'Maubert - Mutualité', 'Michel Bizot', 'Michel-Ange - Auteuil', 'Michel-Ange - Molitor', 'Mirabeau', 'Miromesnil', 'Monceau', 'Montgallet', 'Montparnasse Bienvenue', 'Montreuil-Hôpital', 'Mouton-Duvernet', 'Ménilmontant', 'Nation', 'Nationale', 'Notre-Dame des Champs', 'Notre-Dame-de-Lorette', 'Oberkampf', 'Odéon', 'Olympiades', 'Opéra', 'Ourcq', 'Palais Royal - Musée du Louvre', 'Parmentier', 'Passy', 'Pasteur', 'Pelleport', 'Pereire', 'Pernety', 'Philippe Auguste', 'Picpus', 'Pierre et Marie Curie', 'Pigalle', 'Place Monge', 'Place carnot', "Place d'Italie", 'Place de Clichy', 'Place des Fêtes', 'Plaisance', 'Pointe du Lac', 'Poissonnière', 'Pont Cardinet', 'Pont Marie (Cité des Arts)', 'Pont Neuf', 'Pont de Levallois - Bécon', 'Pont de Neuilly', 'Pont de Sèvres', 'Porte Dauphine', 'Porte Dorée', 'Porte Maillot', "Porte d'Auteuil", "Porte d'Italie", "Porte d'Ivry", "Porte d'Orléans", 'Porte de Bagnolet', 'Porte de Champerret', 'Porte de Charenton', 'Porte de Choisy', 'Porte de Clichy', 'Porte de Clignancourt', 'Porte de Montreuil', 'Porte de Pantin', 'Porte de Saint-Cloud', 'Porte de Saint-Ouen', 'Porte de Vanves', 'Porte de Versailles', 'Porte de Vincennes', 'Porte de la Chapelle', 'Porte de la Villette', 'Porte des Lilas', 'Pré-Saint-Gervais', 'Pyramides', 'Pyrénées', 'Père Lachaise', 'Quai de la Gare', 'Quai de la Rapée', 'Quatre Septembre', 'Rambuteau', 'Ranelagh', 'Raspail', 'Rennes', 'Reuilly - Diderot', 'Richard-Lenoir', 'Richelieu - Drouot', 'Riquet', 'Robespierre', 'Rome', 'Rosny-bois-perrier', 'Rue Saint-Maur', 'Rue de la Pompe', 'Rue des Boulets', 'Rue du Bac', 'Réaumur - Sébastopol', 'République', 'Saint-Ambroise', 'Saint-Augustin', 'Saint-Cloud', 'Saint-Denis - Porte de Paris', 'Saint-Denis - Université', 'Saint-Denis Pleyel', 'Saint-Fargeau', 'Saint-François-Xavier', 'Saint-Georges', 'Saint-Germain-des-Prés', 'Saint-Jacques', 'Saint-Lazare', 'Saint-Mandé', 'Saint-Marcel', 'Saint-Michel', 'Saint-Ouen', 'Saint-Paul (Le Marais)', 'Saint-Philippe du Roule', 'Saint-Placide', 'Saint-Sulpice', 'Saint-Sébastien - Froissart', 'Sentier', 'Serge Gainsbourg', 'Simplon', 'Solférino', 'Stade de France', 'Stalingrad', 'Strasbourg - Saint-Denis', 'Sully - Morland', 'Sèvres - Babylone', 'Sèvres-Lecourbe', 'Ségur', 'Temple', 'Ternes', 'Tolbiac', "Trinité - d'Estienne d'Orves", 'Trocadéro', 'Tuileries', 'Télégraphe', 'Vaneau', 'Varenne', 'Vaugirard', 'Vavin', 'Victor Hugo', 'Villejuif - Gustave Roussy', 'Villejuif - Louis Aragon', 'Villejuif Léo Lagrange', 'Villejuif Paul Vaillant-Couturier', 'Villejuif – Gustave Roussy', 'Villiers', 'Volontaires', 'Voltaire', 'Wagram', 'École Militaire', "Église d'Auteuil", 'Église de Pantin']
326

 statition des donées de tickets :
['Abbesses', 'Aimé Césaire', 'Alexandre Dumas', 'Alma - Marceau', 'Alésia', 'Anatole France', 'Anvers', 'Argentine', 'Arts et Métiers', 'Assemblée Nationale', 'Aubervilliers - Pantin - Quatre Chemins', 'Avenue Émile Zola', 'Avron', "Aéroport d'Orly", 'Bagneux', 'Balard', 'Barbara', 'Barbès - Rochechouart', 'Basilique de Saint-Denis', 'Bastille', 'Bel-Air', 'Belleville', 'Bercy', 'Bibliothèque François Mitterrand', 'Billancourt', 'Bir-Hakeim', 'Blanche', 'Bobigny - Pablo Picasso', 'Bobigny - Pantin - Raymond Queneau', 'Boissière', 'Bonne Nouvelle', 'Boucicaut', 'Boulogne - Jean Jaurès', 'Boulogne - Pont de Saint-Cloud', 'Bourse', 'Bréguet - Sabin', 'Buzenval', 'Bérault', 'Cadet', 'Cambronne', 'Campo-Formio', 'Cardinal Lemoine', 'Carrefour Pleyel', 'Censier - Daubenton', 'Champs-Élysées-Clemenceau', 'Chardon-Lagache', 'Charenton - Écoles', 'Charles Michels', 'Charles de Gaulle-Étoile', 'Charonne', "Chaussée d'Antin - La Fayette", 'Chemin Vert', "Chemin d'Antony", 'Chevaleret', 'Château Rouge', "Château d'Eau", 'Château de Vincennes', 'Château-Landon', 'Châtelet', 'Châtillon - Montrouge', 'Cité', 'Cluny - La Sorbonne', 'Colonel Fabien', 'Commerce', 'Concorde', 'Convention', 'Corentin Cariou', 'Corentin Celton', 'Corvisart', 'Cour Saint-Émilion', 'Courcelles', 'Couronnes', 'Crimée', 'Croix de Chavaux', "Créteil - L'Échat", 'Créteil - Préfecture', 'Créteil - Université', 'Côteaux Beauclair', 'Daumesnil', 'Denfert-Rochereau', 'Dugommier', 'Dupleix', 'Duroc', 'Edgar Quinet', 'Esplanade de la Défense', 'Europe', 'Exelmans', 'Faidherbe - Chaligny', 'Falguière', 'Filles du Calvaire', "Fort d'Aubervilliers", 'Franklin D. Roosevelt', 'Félix Faure', 'Gallieni', 'Gambetta', "Gare d'Austerlitz", 'Gare de Lyon', "Gare de l'Est", 'Gare du Nord', 'Garibaldi', 'Gaîté', 'George V', 'Glacière', 'Goncourt', 'Grands Boulevards', 'Guy Môquet', 'Havre - Caumartin', 'Hoche', 'Hôtel de Ville', 'Invalides', 'Issy - Val de Seine', 'Iéna', 'Jacques Bonsergent', 'Jasmin', 'Jaurès', 'Javel - André Citroën', 'Jourdain', 'Jules Joffrin', 'Jussieu', 'Kléber', "L'Haÿ-les-Roses", 'La Chapelle', 'La Courneuve - 8 Mai 1945', 'La Dhuys', 'La Défense', 'La Fourche', 'La Motte-Picquet - Grenelle', 'La Muette', 'La Tour-Maubourg', 'Lamarck - Caulaincourt', 'Laumière', 'Le Peletier', 'Ledru-Rollin', 'Les Gobelins', 'Les Halles', 'Les Sablons', 'Liberté', 'Liège', 'Louis Blanc', 'Louise Michel', 'Lourmel', 'Louvre - Rivoli', 'Mabillon', 'Madeleine', "Mairie d'Aubervilliers", "Mairie d'Issy", "Mairie d'Ivry", 'Mairie de Montreuil', 'Mairie de Saint-Ouen', 'Mairie des Lilas', 'Maison Blanche', 'Maisons-Alfort - Les Juilliottes', 'Maisons-Alfort - Stade', 'Malakoff - Plateau de Vanves', 'Malakoff - Rue Étienne Dolet', 'Malesherbes', 'Maraîchers', 'Marcadet - Poissonniers', 'Marcel Sembat', 'Maubert - Mutualité', 'Michel Bizot', 'Michel-Ange - Auteuil', 'Michel-Ange - Molitor', 'Mirabeau', 'Miromesnil', 'Monceau', 'Montgallet', 'Montparnasse - Bienvenüe', 'Montreuil - Hôpital', 'Montrouge', 'Mouton-Duvernet', 'Ménilmontant', 'Nation', 'Nationale', 'Notre-Dame-de-Lorette', 'Notre-Dame-des-Champs', 'Oberkampf', 'Odéon', 'Olympiades', 'Opéra', 'Ourcq', 'Palais Royal - Musée du Louvre', 'Parmentier', 'Passy', 'Pasteur', 'Pereire', 'Pernety', 'Philippe Auguste', 'Picpus', 'Pierre et Marie Curie', 'Pigalle', 'Place Monge', "Place d'Italie", 'Place de Clichy', 'Place des Fêtes', 'Plaisance', 'Poissonnière', 'Pont Cardinet', 'Pont Marie', 'Pont Neuf', 'Pont de Levallois - Bécon', 'Pont de Neuilly', 'Pont de Sèvres', 'Porte Dauphine', 'Porte Dorée', 'Porte Maillot', "Porte d'Auteuil", "Porte d'Italie", "Porte d'Ivry", "Porte d'Orléans", 'Porte de Bagnolet', 'Porte de Champerret', 'Porte de Charenton', 'Porte de Choisy', 'Porte de Clichy', 'Porte de Clignancourt', 'Porte de Montreuil', 'Porte de Pantin', 'Porte de Saint-Cloud', 'Porte de Saint-Ouen', 'Porte de Vanves', 'Porte de Versailles', 'Porte de Vincennes', 'Porte de la Chapelle', 'Porte de la Villette', 'Porte des Lilas', 'Pyramides', 'Pyrénées', 'Père Lachaise', 'Quai de la Gare', 'Quai de la Rapée', 'Quatre-Septembre', 'Rambuteau', 'Ranelagh', 'Raspail', 'Rennes', 'Reuilly - Diderot', 'Richard-Lenoir', 'Richelieu - Drouot', 'Riquet', 'Robespierre', 'Romainville - Carnot', 'Rome', 'Rosny-Bois-Perrier', 'Rue Saint-Maur', 'Rue de la Pompe', 'Rue des Boulets', 'Rue du Bac', 'Réaumur - Sébastopol', 'République', 'Saint-Ambroise', 'Saint-Augustin', 'Saint-Denis - Porte de Paris', 'Saint-Denis - Université', 'Saint-Denis Pleyel', 'Saint-François-Xavier', 'Saint-Georges', 'Saint-Germain-des-Prés', 'Saint-Jacques', 'Saint-Lazare', 'Saint-Mandé', 'Saint-Marcel', 'Saint-Michel', 'Saint-Ouen', 'Saint-Paul', 'Saint-Philippe du Roule', 'Saint-Placide', 'Saint-Sulpice', 'Saint-Sébastien - Froissart', 'Sentier', 'Serge Gainsbourg', 'Simplon', 'Solférino', 'Stalingrad', 'Strasbourg - Saint-Denis', 'Sully - Morland', 'Sèvres - Babylone', 'Sèvres - Lecourbe', 'Ségur', 'Temple', 'Ternes', 'Tolbiac', "Trinité - d'Estienne d'Orves", 'Trocadéro', 'Tuileries', 'Télégraphe', 'Vaneau', 'Varenne', 'Vaugirard', 'Vavin', 'Victor Hugo', 'Villejuif - Gustave Roussy', 'Villejuif - Louis Aragon', 'Villejuif - Léo Lagrange', 'Villejuif - Paul Vaillant-Couturier', 'Villiers', 'Volontaires', 'Voltaire', 'Wagram', 'École Militaire', 'École Vétérinaire de Maisons-Alfort', "Église d'Auteuil", 'Église de Pantin', 'Étienne Marcel']
304

In [46]:




# 1. Récupérer les communes présentes dans le résultat filtré et normalisé 

stations_trouvees = [normaliser(nom) for nom in df_data_metro_paris["Libelle station"].unique()]


# 2. Trouver les communes absentes après normalisation des noms 
stations_non_trouvees = set([normaliser(nom) for nom in liste_stations]) - set(stations_trouvees)
if (len(stations_non_trouvees)== 0):
    print ("toutes trouvées")
else :
    print("stations non trouvées :")
    print(sorted(stations_non_trouvees))
    print(len(stations_non_trouvees))

stations non trouvées :
['aeroport d orly', 'bagneux', 'chemin d antony', 'issy val de seine', 'l hay les roses', 'la defense', 'montrouge', 'pont marie', 'romainville carnot', 'saint paul']
10

In [26]:
df_data_metro[df_data_metro["Commune nom"] == 'Courbevoie']

# Aeroport d'Orly pas de correspondance alors qu'il est dans les 2 probleme de "" et ''
# 'Bagneux' => 'Bagneux - Lucie Aubrac'
# pas de station de metro chemin d'anthony 

# Issy val sur seine existe pas => station rer mais le station de metro Issy RER va ouvrir 
#"L'Haÿ-les-Roses" pas de correspondance alors qu'il est dans les 2 probleme de "" et ''
# 'La Défense (Grande Arche)' <=> 'La Defense'
#Montrouge => Marie-Montrouge
# Pont Marie => 'Pont Marie (Cité des Arts)
# romainville carnot => pas de correspondance 
# Saint Paul => 'Saint-Paul (Le Marais)'
# Issy-val-sur-seine et chemin d'anthony ne sont pas a retirer 
'

('Courbevoie',
 'Puteaux',
 'Noisy-le-Sec',
 'Rosny-sous-Bois',
 'Montreuil',
 'Lilas')

In [27]:
df_data_cible = df_data_cible[df_data_cible["finish"] == 1]

In [28]:
sorted(df_data_metro['Libelle station'].unique())

['Abbesses',
 'Aimé Césaire',
 'Airbus Colomiers Ramassiers',
 'Airbus Saint-Martin',
 'Alexandre Dumas',
 'Alma - Marceau',
 'Alsace',
 'Alésia',
 'Ampère Victor Hugo',
 'Anatole France',
 'Antonypole',
 'Anvers',
 'Arcueil - Cachan',
 'Argentine',
 'Argoulets',
 'Arts et Métiers',
 'Arènes',
 'Asnières - Gennevilliers Les Courtilles',
 'Assemblée Nationale',
 'Atalante',
 'Aubervilliers-Pantin Quatre Chemins',
 'Aulnay',
 'Avenue Émile Zola',
 'Avron',
 'Aéroport Charles-de-Gaulle T2',
 'Aéroport Charles-de-Gaulle T4',
 'Aéroport d’Orly',
 'Bagatelle',
 'Bagneux - Lucie Aubrac',
 'Baille',
 'Balard',
 'Balma Gramont',
 'Barbara',
 'Barbès - Rochechouart',
 'Barrière de Paris',
 'Basilique de Saint-Denis',
 'Basso Cambo',
 'Bastille',
 'Beaulieu – Université',
 'Bel-Air',
 'Bellecour',
 'Bellefontaine',
 'Belleville',
 'Bercy',
 'Bibliothèque François Mitterrand',
 'Billancourt',
 'Bir-Hakeim',
 'Blanche',
 'Bobigny Pablo Picasso',
 'Bobigny-Pantin - Raymond Queneau',
 'Bois Blancs',
 'Bois-Colombes',
 'Boissière',
 'Bolivar',
 'Bondy',
 'Bonne Nouvelle',
 'Bonnefoy',
 'Borderouge',
 'Botzaris',
 'Boucicaut',
 'Bougainville',
 'Boulevard-de-Suisse - Ponts-Jumeaux ',
 'Boulogne Jean Jaurès',
 'Boulogne Pont de Saint-Cloud',
 'Bourg',
 'Bourgogne',
 'Bourse',
 'Brochant',
 'Brotteaux',
 'Bry-Villiers-Champigny',
 'Bréguet-Sabin',
 'Buttes Chaumont',
 'Buzenval',
 'Bécon-les-Bruyères',
 'Bérault',
 'CEA Saint-Aubin',
 'CHU – Centre O.Lambret',
 'Cadet',
 'Cambronne',
 'Campo-Formio',
 'Canal du Midi',
 'Canteleu',
 'Capitole',
 'Cardinal Lemoine',
 'Carliers',
 'Carmes',
 'Carrefour Pleyel',
 'Castellane',
 'Caulier',
 'Censier - Daubenton',
 'Cesson – Viasilva',
 'Champigny Centre',
 'Champs-Élysées - Clemenceau',
 'Chardon Lagache',
 'Charenton - Écoles',
 'Charles Michels',
 'Charles de Gaulle',
 'Charles de Gaulle - Etoile',
 'Charonne',
 'Charpennes',
 'Chartreux',
 "Chaussée d'Antin - La Fayette",
 'Chelles',
 'Chemin Vert',
 'Chevaleret',
 'Chevilly-larue',
 'Château Landon',
 'Château Rouge',
 "Château d'Eau",
 'Château de Vincennes',
 'Châtelet',
 'Châtillon-Montrouge',
 'Cinq Avenues Longchamp',
 'Cité',
 'Cité Scientifique Pr Gabillard',
 'Clemenceau',
 'Cleunay',
 'Clichy - Montfermeil',
 'Cluny - La Sorbonne',
 'Colbert',
 'Colombier',
 'Colomiers – Gare',
 'Colonel Fabien',
 'Commerce',
 'Compans Caffarelli',
 'Concorde',
 'Convention',
 'Cordeliers',
 'Corentin Cariou',
 'Corentin Celton',
 'Cormontaigne',
 'Corvisart',
 'Coteaux beauclair',
 'Cour Saint-Emilion',
 'Courcelles',
 'Couronnes',
 'Crimée',
 'Croix Centre',
 'Croix Paquet',
 'Croix de Chavaux',
 'Croix-Rousse',
 "Créteil - L'Échat",
 'Créteil - Préfecture',
 'Créteil - Université',
 'Cuire',
 'Cusset',
 'Danube',
 'Daumesnil',
 'Debourg',
 'Denfert-Rochereau',
 'Drancy - Bobigny',
 'Dugommier',
 'Dupleix',
 'Duroc',
 'Désirée Clary',
 'Ecole Vétérinaire de Maisons-Alfort',
 'Edgar Quinet',
 'Empalot',
 'Epeule Montesquieu',
 'Esplanade de la Défense',
 'Esquirol',
 'Estrangin',
 'Etienne Marcel',
 'Europe',
 'Eurotéléport',
 'Exelmans',
 'Faculté de Pharmacie',
 'Faidherbe - Chaligny',
 'Falguière',
 'Filles du Calvaire',
 'Fives',
 'Flachet',
 'Foch',
 'Fondeyre',
 'Fontaine Lestang',
 "Fort d'Aubervilliers",
 "Fort d'Issy - Vanves - Clamart",
 'Fort de Mons',
 'Frais Vallon',
 'Franklin D. Roosevelt',
 'François Verdier',
 'Front Populaire',
 'Félix Faure',
 'Gabriel Péri',
 'Gallieni',
 'Gambetta',
 'Gare Jean Lebas Roubaix',
 'Gare Lille Europe',
 'Gare Lille Flandres',
 'Gare Part-Dieu V.Merle',
 "Gare d'Austerlitz",
 'Gare de Lyon',
 'Gare de Tourcoing',
 'Gare de Vaise',
 'Gare de Vénissieux',
 "Gare de l'Est",
 'Gare du Nord',
 'Gare d’Oullins',
 'Gares',
 'Garibaldi',
 'Gaîté',
 'George V',
 'Glacière',
 'Goncourt',
 'Gorge de Loup',
 'Grands Boulevards',
 'Grange Blanche',
 'Gratte Ciel',
 'Gros Chêne',
 'Guillotière Gabriel Péri',
 'Guy Môquet',
 'Gèze',
 'Havre-Caumartin',
 'Henri Fréville',
 'Hoche',
 'Hénon',
 'Hôpital bicêtre',
 'Hôtel de Ville',
 'Hôtel de Ville Louis Pradel',
 'INPT',
 'Invalides',
 'Issy RER',
 'Italie ',
 'Iéna',
 'J.F.Kennedy',
 'Jacques Bonsergent',
 'Jacques Cartier',
 'Jasmin',
 'Jaurès',
 'Javel - André Citroën',
 'Jean Jaurès',
 'Jean Macé',
 'Jean-Maga',
 'Jean-Rieux',
 'Jeanne d’Arc',
 'Joliette',
 'Jolimont',
 'Joliot-Curie – Chateaubriand',
 'Jourdain',
 'Jules Ferry',
 'Jules Guesde',
 'Jules Joffrin',
 'Jussieu',
 'Kléber',
 'La Blancarde',
 'La Chapelle',
 'La Courneuve - 8 Mai 1945',
 'La Courneuve - Six Routes',
 'La Courrouze',
 'La Défense (Grande Arche)',
 'La Fourche',
 'La Fourragère',
 'La Motte-Picquet - Grenelle',
 'La Muette',
 'La Poterie',
 'La Rose',
 'La Timone',
 'La Tour-Maubourg',
 'La Vache',
 'La dhuys',
 'Labège Enova',
 'Labège La Cadène',
 'Laennec',
 'Lamarck - Caulaincourt',
 'Laumière',
 'Laurent Bonnevay',
 'Le Blanc-Mesnil',
 'Le Blosne',
 'Le Bourget - Aéroport',
 'Le Bourget RER',
 'Le Kremlin-Bicêtre',
 'Le Mesnil-Amelot',
 'Le Peletier',
 'Le Vert de Maisons',
 'Ledru-Rollin',
 'Les Agnettes',
 'Les Ardoines',
 'Les Gayeulles',
 'Les Gobelins',
 'Les Grésillons',
 'Les Halles',
 'Les Prés Edgard Pisani',
 'Les Sablons',
 'Liberté',
 'Lille CHU-Eurasanté',
 'Lille Grand Palais',
 "Limayrac - Cité de l'Espace",
 'Liège',
 'Lomme Lambersart Arthur Notebart',
 'Lomme Saint Philibert',
 'Louis Armand',
 'Louis Blanc',
 'Louise Michel',
 'Lourmel',
 'Louvre - Rivoli',
 'L’Haÿ-les-roses',
 'L’Ormeau',
 'Mabilais',
 'Mabillon',
 'Madeleine',
 "Mairie d'Aubervilliers",
 "Mairie d'Issy",
 "Mairie d'Ivry",
 'Mairie de Clichy',
 'Mairie de Croix',
 'Mairie de Lille',
 'Mairie de Mons',
 'Mairie de Montreuil',
 'Mairie de Montrouge',
 'Mairie de Saint-Ouen',
 'Mairie des Lilas',
 'Mairie d’Hellemmes',
 'Maison Blanche',
 'Maison des Enfants',
 'Maisons-Alfort - Les Juilliottes',
 'Maisons-Alfort - Stade',
 'Malakoff - Plateau de Vanves',
 'Malakoff - Rue Etienne Dolet',
 'Malesherbes',
 'Malpassé',
 'Maraîchers',
 'Marbrerie',
 'Marcadet - Poissonniers',
 'Marcel Sembat',
 'Marengo SNCF',
 'Marx Dormoy',
 'Massy - Palaiseau',
 'Massy Opéra',
 'Masséna',
 'Maubert - Mutualité',
 'Mercure',
 'Mermoz',
 'Mermoz – Pinel',
 'Michel Bizot',
 'Michel-Ange - Auteuil',
 'Michel-Ange - Molitor',
 'Minimes Claude Nougaro',
 'Mirabeau',
 'Mirail Université',
 'Miromesnil',
 'Mitterie',
 'Monceau',
 'Monplaisir Lumière',
 'Mons Sarts',
 'Montaudran - Piste des Géants',
 'Montaudran Innovation CampusAirbus Defense & Space',
 'Montebello',
 'Montgallet',
 'Montparnasse Bienvenue',
 'Montreuil-Hôpital',
 'Mouton-Duvernet',
 'Ménilmontant',
 'Nanterre La Boule',
 'Nanterre La Folie',
 'Nation',
 'National',
 'Nationale',
 'Noailles',
 'Nogent - Le Perreux',
 'Noisy – Champs',
 'Notre-Dame des Champs',
 'Notre-Dame du Mont',
 'Notre-Dame-de-Lorette',
 'Oberkampf',
 'Odéon',
 'Olympiades',
 'Opéra',
 'Orsay - Gif',
 'Oullins Centre',
 'Ourcq',
 'Palais Royal - Musée du Louvre',
 'Palais de Justice',
 'Palaiseau',
 'Parc Technologique du canal',
 'Parc des Expositions',
 'Parilly',
 'Parmentier',
 'Passy',
 'Pasteur',
 'Patte d’Oie',
 'Pelleport',
 'Pereire',
 'Pernety',
 'Perrache',
 'Phalempins',
 'Philippe Auguste',
 'Picpus',
 'Pierre et Marie Curie',
 'Pigalle',
 'Place Guichard',
 'Place Jean Jaurès',
 'Place Monge',
 'Place carnot',
 "Place d'Italie",
 'Place de Clichy',
 'Place des Fêtes',
 'Plaisance',
 'Pointe du Lac',
 'Poissonnière',
 'Pont Cardinet',
 'Pont Marie (Cité des Arts)',
 'Pont Neuf',
 'Pont Supérieur',
 'Pont de Bois',
 'Pont de Bondy',
 'Pont de Levallois - Bécon',
 'Pont de Neuilly',
 'Pont de Neuville',
 'Pont de Sèvres',
 'Pontchaillou',
 'Port de Lille',
 'Porte Dauphine',
 'Porte Dorée',
 'Porte Maillot',
 "Porte d'Auteuil",
 "Porte d'Italie",
 "Porte d'Ivry",
 "Porte d'Orléans",
 'Porte de Bagnolet',
 'Porte de Champerret',
 'Porte de Charenton',
 'Porte de Choisy',
 'Porte de Clichy',
 'Porte de Clignancourt',
 'Porte de Douai',
 'Porte de Montreuil',
 'Porte de Pantin',
 'Porte de Saint-Cloud',
 'Porte de Saint-Ouen',
 'Porte de Valenciennes',
 'Porte de Vanves',
 'Porte de Versailles',
 'Porte de Vincennes',
 'Porte de la Chapelle',
 'Porte de la Villette',
 'Porte des Lilas',
 'Porte des Postes',
 'Porte d’Arras',
 'Pré-Saint-Gervais',
 'Pyramides',
 'Pyrénées',
 'Père Lachaise',
 'Périer',
 'Quai de la Gare',
 'Quai de la Rapée',
 'Quatre Septembre',
 'Rambuteau',
 'Ramonville',
 'Ranelagh',
 'Rangueil',
 'Raspail',
 'Raynal',
 'Rennes',
 'Reuilly - Diderot',
 'Reynerie',
 'Richard-Lenoir',
 'Richelieu - Drouot',
 'Rihour',
 'Riquet',
 'Robespierre',
 'Rome',
 'Rond Point du Prado',
 'Roseraie',
 'Rosny-bois-perrier',
 'Roubaix Charles de Gaulle',
 'Roubaix Grande Place',
 'Rue Saint-Maur',
 'Rue de la Pompe',
 'Rue des Boulets',
 'Rue du Bac',
 'Rueil - Suresnes - Mont Valérien',
 'Réaumur - Sébastopol',
 'Réformés Canebière',
 'République',
 'République Beaux-arts',
 'République Villeurbanne',
 'Saint Agne SNCF',
 'Saint Cyprien République',
 'Saint Maurice Pellevoisin',
 'Saint michel Marcel Langer',
 'Saint-Ambroise',
 'Saint-Augustin',
 'Saint-Barnabé',
 'Saint-Charles',
 'Saint-Cloud',
 'Saint-Denis - Porte de Paris',
 'Saint-Denis - Université',
 'Saint-Denis Pleyel',
 'Saint-Fargeau',
 'Saint-François-Xavier',
 'Saint-Genis-Laval Hôpitaux Sud',
 'Saint-Georges',
 'Saint-Germain',
 'Saint-Germain-des-Prés',
 'Saint-Jacques',
 'Saint-Jacques – Gaîté',
 'Saint-Just',
 'Saint-Lazare',
 'Saint-Mandé',
 'Saint-Marcel',
 'Saint-Maur - Créteil',
 'Saint-Michel',
 'Saint-Ouen',
 'Saint-Paul (Le Marais)',
 'Saint-Philippe du Roule',
 'Saint-Placide',
 'Saint-Quentin Est',
 'Saint-Sulpice',
 'Saint-Sébastien - Froissart',
 'Sainte-Anne',
 'Sainte-Marguerite Dromel',
 'Sans Souci',
 'Saouzelong',
 'Satory',
 'Saxe – Gambetta',
 'Sentier',
 'Sept-Deniers Stade Toulousain',
 'Serge Gainsbourg',
 'Sevran - Beaudottes',
 'Sevran - Livry',
 'Simplon',
 'Solférino',
 'Square Flandres',
 'Stade de France',
 'Stade de Gerland Le LOU',
 'Stalingrad',
 'Strasbourg - Saint-Denis',
 'Sully - Morland',
 'Sèvres - Babylone',
 'Sèvres-Lecourbe',
 'Ségur',
 'Temple',
 'Ternes',
 'Thiais – Orly',
 'Tolbiac',
 'Toulouse-Lautrec',
 'Tourcoing C.H. Dron',
 'Tourcoing Centre',
 'Triangle',
 'Triangle de Gonesse',
 "Trinité - d'Estienne d'Orves",
 'Triolo',
 'Trocadéro',
 'Trois Cocus',
 'Tuileries',
 'Télégraphe',
 'Université Paul Sabatier',
 'Val de Fontenay',
 'Valmy',
 'Vaneau',
 'Varenne',
 'Vaugirard',
 'Vaulx-en-Velin La Soie',
 'Vavin',
 'Versailles Chantiers',
 'Victor Hugo',
 'Vieux Lyon',
 'Vieux Port',
 'Villejean – Université',
 'Villejuif - Gustave Roussy',
 'Villejuif - Louis Aragon',
 'Villejuif Léo Lagrange',
 'Villejuif Paul Vaillant-Couturier',
 'Villejuif – Gustave Roussy',
 'Villeneuve d’Ascq 4 Cantons Stade Pierre Mauroy',
 'Villeneuve d’Ascq Hôtel de Ville',
 'Villiers',
 'Vitry Centre',
 'Volontaires',
 'Voltaire',
 'Wagram',
 'Wasquehal Hôtel de Ville',
 'Wasquehal Pavé de Lille',
 'Wazemmes',
 'École Militaire',
 "Église d'Auteuil",
 'Église de Pantin']

In [6]:
df_data_metro[df_data_metro["Libelle station"] == 'République']

,ID Line,Libelle Line,Libelle station,Longitude,Latitude,finish,Commune nom,Commune code Insee
49,5,a,République,-1.679256,48.109683,1,Rennes,35238
273,15,3,République,2.363302,48.867512,1,Paris 3ème,75103
325,18,5,République,2.363302,48.867512,1,Paris 3ème,75103
427,23,8,République,2.363302,48.867512,1,Paris 3ème,75103
473,24,9,République,2.363302,48.867512,1,Paris 3ème,75103
514,27,11,République,2.363302,48.867512,1,Paris 3ème,75103

In [13]:
sorted(liste_stations)

['Abbesses',
 'Aimé Césaire',
 'Alexandre Dumas',
 'Alma - Marceau',
 'Alésia',
 'Anatole France',
 'Anvers',
 'Argentine',
 'Arts et Métiers',
 'Assemblée Nationale',
 'Aubervilliers - Pantin - Quatre Chemins',
 'Avenue Émile Zola',
 'Avron',
 "Aéroport d'Orly",
 'Bagneux',
 'Balard',
 'Barbara',
 'Barbès - Rochechouart',
 'Basilique de Saint-Denis',
 'Bastille',
 'Bel-Air',
 'Belleville',
 'Bercy',
 'Bibliothèque François Mitterrand',
 'Billancourt',
 'Bir-Hakeim',
 'Blanche',
 'Bobigny - Pablo Picasso',
 'Bobigny - Pantin - Raymond Queneau',
 'Boissière',
 'Bonne Nouvelle',
 'Boucicaut',
 'Boulogne - Jean Jaurès',
 'Boulogne - Pont de Saint-Cloud',
 'Bourse',
 'Bréguet - Sabin',
 'Buzenval',
 'Bérault',
 'Cadet',
 'Cambronne',
 'Campo-Formio',
 'Cardinal Lemoine',
 'Carrefour Pleyel',
 'Censier - Daubenton',
 'Champs-Élysées-Clemenceau',
 'Chardon-Lagache',
 'Charenton - Écoles',
 'Charles Michels',
 'Charles de Gaulle-Étoile',
 'Charonne',
 "Chaussée d'Antin - La Fayette",
 'Chemin Vert',
 "Chemin d'Antony",
 'Chevaleret',
 'Château Rouge',
 "Château d'Eau",
 'Château de Vincennes',
 'Château-Landon',
 'Châtelet',
 'Châtillon - Montrouge',
 'Cité',
 'Cluny - La Sorbonne',
 'Colonel Fabien',
 'Commerce',
 'Concorde',
 'Convention',
 'Corentin Cariou',
 'Corentin Celton',
 'Corvisart',
 'Cour Saint-Émilion',
 'Courcelles',
 'Couronnes',
 'Crimée',
 'Croix de Chavaux',
 "Créteil - L'Échat",
 'Créteil - Préfecture',
 'Créteil - Université',
 'Côteaux Beauclair',
 'Daumesnil',
 'Denfert-Rochereau',
 'Dugommier',
 'Dupleix',
 'Duroc',
 'Edgar Quinet',
 'Esplanade de la Défense',
 'Europe',
 'Exelmans',
 'Faidherbe - Chaligny',
 'Falguière',
 'Filles du Calvaire',
 "Fort d'Aubervilliers",
 'Franklin D. Roosevelt',
 'Félix Faure',
 'Gallieni',
 'Gambetta',
 "Gare d'Austerlitz",
 'Gare de Lyon',
 "Gare de l'Est",
 'Gare du Nord',
 'Garibaldi',
 'Gaîté',
 'George V',
 'Glacière',
 'Goncourt',
 'Grands Boulevards',
 'Guy Môquet',
 'Havre - Caumartin',
 'Hoche',
 'Hôtel de Ville',
 'Invalides',
 'Issy - Val de Seine',
 'Iéna',
 'Jacques Bonsergent',
 'Jasmin',
 'Jaurès',
 'Javel - André Citroën',
 'Jourdain',
 'Jules Joffrin',
 'Jussieu',
 'Kléber',
 "L'Haÿ-les-Roses",
 'La Chapelle',
 'La Courneuve - 8 Mai 1945',
 'La Dhuys',
 'La Défense',
 'La Fourche',
 'La Motte-Picquet - Grenelle',
 'La Muette',
 'La Tour-Maubourg',
 'Lamarck - Caulaincourt',
 'Laumière',
 'Le Peletier',
 'Ledru-Rollin',
 'Les Gobelins',
 'Les Halles',
 'Les Sablons',
 'Liberté',
 'Liège',
 'Louis Blanc',
 'Louise Michel',
 'Lourmel',
 'Louvre - Rivoli',
 'Mabillon',
 'Madeleine',
 "Mairie d'Aubervilliers",
 "Mairie d'Issy",
 "Mairie d'Ivry",
 'Mairie de Montreuil',
 'Mairie de Saint-Ouen',
 'Mairie des Lilas',
 'Maison Blanche',
 'Maisons-Alfort - Les Juilliottes',
 'Maisons-Alfort - Stade',
 'Malakoff - Plateau de Vanves',
 'Malakoff - Rue Étienne Dolet',
 'Malesherbes',
 'Maraîchers',
 'Marcadet - Poissonniers',
 'Marcel Sembat',
 'Maubert - Mutualité',
 'Michel Bizot',
 'Michel-Ange - Auteuil',
 'Michel-Ange - Molitor',
 'Mirabeau',
 'Miromesnil',
 'Monceau',
 'Montgallet',
 'Montparnasse - Bienvenüe',
 'Montreuil - Hôpital',
 'Montrouge',
 'Mouton-Duvernet',
 'Ménilmontant',
 'Nation',
 'Nationale',
 'Notre-Dame-de-Lorette',
 'Notre-Dame-des-Champs',
 'Oberkampf',
 'Odéon',
 'Olympiades',
 'Opéra',
 'Ourcq',
 'Palais Royal - Musée du Louvre',
 'Parmentier',
 'Passy',
 'Pasteur',
 'Pereire',
 'Pernety',
 'Philippe Auguste',
 'Picpus',
 'Pierre et Marie Curie',
 'Pigalle',
 'Place Monge',
 "Place d'Italie",
 'Place de Clichy',
 'Place des Fêtes',
 'Plaisance',
 'Poissonnière',
 'Pont Cardinet',
 'Pont Marie',
 'Pont Neuf',
 'Pont de Levallois - Bécon',
 'Pont de Neuilly',
 'Pont de Sèvres',
 'Porte Dauphine',
 'Porte Dorée',
 'Porte Maillot',
 "Porte d'Auteuil",
 "Porte d'Italie",
 "Porte d'Ivry",
 "Porte d'Orléans",
 'Porte de Bagnolet',
 'Porte de Champerret',
 'Porte de Charenton',
 'Porte de Choisy',
 'Porte de Clichy',
 'Porte de Clignancourt',
 'Porte de Montreuil',
 'Porte de Pantin',
 'Porte de Saint-Cloud',
 'Porte de Saint-Ouen',
 'Porte de Vanves',
 'Porte de Versailles',
 'Porte de Vincennes',
 'Porte de la Chapelle',
 'Porte de la Villette',
 'Porte des Lilas',
 'Pyramides',
 'Pyrénées',
 'Père Lachaise',
 'Quai de la Gare',
 'Quai de la Rapée',
 'Quatre-Septembre',
 'Rambuteau',
 'Ranelagh',
 'Raspail',
 'Rennes',
 'Reuilly - Diderot',
 'Richard-Lenoir',
 'Richelieu - Drouot',
 'Riquet',
 'Robespierre',
 'Romainville - Carnot',
 'Rome',
 'Rosny-Bois-Perrier',
 'Rue Saint-Maur',
 'Rue de la Pompe',
 'Rue des Boulets',
 'Rue du Bac',
 'Réaumur - Sébastopol',
 'République',
 'Saint-Ambroise',
 'Saint-Augustin',
 'Saint-Denis - Porte de Paris',
 'Saint-Denis - Université',
 'Saint-Denis Pleyel',
 'Saint-François-Xavier',
 'Saint-Georges',
 'Saint-Germain-des-Prés',
 'Saint-Jacques',
 'Saint-Lazare',
 'Saint-Mandé',
 'Saint-Marcel',
 'Saint-Michel',
 'Saint-Ouen',
 'Saint-Paul',
 'Saint-Philippe du Roule',
 'Saint-Placide',
 'Saint-Sulpice',
 'Saint-Sébastien - Froissart',
 'Sentier',
 'Serge Gainsbourg',
 'Simplon',
 'Solférino',
 'Stalingrad',
 'Strasbourg - Saint-Denis',
 'Sully - Morland',
 'Sèvres - Babylone',
 'Sèvres - Lecourbe',
 'Ségur',
 'Temple',
 'Ternes',
 'Tolbiac',
 "Trinité - d'Estienne d'Orves",
 'Trocadéro',
 'Tuileries',
 'Télégraphe',
 'Vaneau',
 'Varenne',
 'Vaugirard',
 'Vavin',
 'Victor Hugo',
 'Villejuif - Gustave Roussy',
 'Villejuif - Louis Aragon',
 'Villejuif - Léo Lagrange',
 'Villejuif - Paul Vaillant-Couturier',
 'Villiers',
 'Volontaires',
 'Voltaire',
 'Wagram',
 'École Militaire',
 'École Vétérinaire de Maisons-Alfort',
 "Église d'Auteuil",
 'Église de Pantin',
 'Étienne Marcel']

In [6]:
df = df_data_metro[df_data_metro["Commune nom"].isin(liste_communes)]

             Commune nom  Commune code Insee
205              Puteaux               92062
206           Courbevoie               92026
207    Neuilly-sur-Seine               92051
208    Neuilly-sur-Seine               92051
209          Paris 17ème               75117
..                   ...                 ...
677         La Courneuve               93027
693         La Courneuve               93027
694          Saint-Denis               93200
703               Antony               92002
704  Paray-Vieille-Poste               91479

[431 rows x 2 columns]

In [9]:
print(df[["Commune nom", "Commune code Insee"]].drop_duplicates())

              Commune nom  Commune code Insee
205               Puteaux               92062
206            Courbevoie               92026
207     Neuilly-sur-Seine               92051
209           Paris 17ème               75117
212            Paris 8ème               75108
216             Paris 1er               75101
219            Paris 4ème               75104
222           Paris 12ème               75112
227           Saint-Mandé               94067
228             Vincennes               94080
230           Paris 16ème               75116
238           Paris 18ème               75118
239            Paris 9ème               75109
242           Paris 10ème               75110
244           Paris 19ème               75119
248           Paris 11ème               75111
252           Paris 20ème               75120
255      Levallois-Perret               92044
267            Paris 2ème               75102
271            Paris 3ème               75103
279              Bagnolet               93006
298            Paris 6ème               75106
303           Paris 15ème               75115
304           Paris 14ème               75114
310             Montrouge               92049
311               Bagneux               92007
313               Bobigny               93008
314                Pantin               93055
331            Paris 5ème               75105
332           Paris 13ème               75113
363          La Courneuve               93027
364         Aubervilliers               93001
395        Ivry-sur-Seine               94041
398    Le Kremlin-Bicêtre               94043
399             Villejuif               94076
417            Paris 7ème               75107
440     Charenton-le-Pont               94018
442        Maisons-Alfort               94046
445               Créteil               94028
449  Boulogne-Billancourt               92012
483             Montreuil               93048
522                 Lilas               93045
525           Saint-Denis               93066
552   Issy-les-Moulineaux               92040
554             Châtillon               92020
555              Malakoff               92046
574            Saint-Ouen               93070
583                Clichy               92024
584    Asnières-sur-Seine               92004
626           Romainville               93063
627          Noisy-le-Sec               93053
630       Rosny-sous-Bois               93064
635       L'Haÿ-les-Roses               94038
638   Paray-Vieille-Poste               91479
655           Saint-Cloud               92064
664           Saint-Denis               93200
665           Saint-Denis               93210
703                Antony               92002